### カイ二乗適合度検定
多項分布の各項の生起確率$p_1,p_2,\cdots,p_a$がある一定の法則に従っているという仮説の検定は一般に適合度検定と呼ばれる。
尤度比検定やエフィシェントスコアに基づく検定が用いられる。後者は$\chi^2$適合度検定の名で頻用される。
$np_i(\boldsymbol{\tilde{\beta}})(i=1,\cdots,a)$は仮説モデルの下でのあてはめ値であり、とくに帰無仮説が単純仮説の場合などでは知論度数と呼ばれる。
$$
\chi^2=\sum\frac{(観測度数-理論度数)^2}{理論度数}
$$
と表すことも多い。観測値へのモデルのあてはまり度を測るという意味で適合度検定と呼ぶ。
漸近分布は$\chi^2$分布で、その自由度は
$$
\begin{align}
\nu&=(多項分布の自由度)-(あてはめたモデルの母数の個数)\\
&=(項の数(a)-1)-(あてはめたモデルの母数の個数)
\end{align}
$$
で与えられる。

In [14]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'乱数':np.arange(10),
                    '度数':[10,9,7,7,9,6,10,17,14,11]})
df1

   乱数  度数
0   0  10
1   1   9
2   2   7
3   3   7
4   4   9
5   5   6
6   6  10
7   7  17
8   8  14
9   9  11

In [253]:
from scipy.stats import chi2

n = df1['度数'].sum()
p = 1/10
npk = n * p

chi2_value = np.sum((df1['度数'].values - npk)**2/npk)
print('chi2 value ', chi2_value)

nu = 10 - 1
chi2_25 = chi2.ppf(0.75,df=nu)
chi2_50 = chi2.ppf(0.5,df=nu)
print('25%点 ', chi2_25)
print('50%点 ', chi2_50)

p_value = chi2.sf(chi2_value, df=nu)
print('p value ', p_value)

chi2 value  10.2
25%点  11.388751440470372
50%点  8.342832692252955
p value  0.3345381516340064

多項分布の尤度
$$
L(\boldsymbol{p})=\frac{n!}{y_1!\cdots y_a!}p_1^{y_1}\cdots p_a^{y_a}
$$
に基づいて尤度比検定を作るには次のように考える。
特別な構造を仮定しないとき最尤推定量
$$
\tilde{p}_k=y_k/n,\hspace{3mm}k=1,\cdots,a
$$
が得られる。一方セル確率が
$$
$H_0:p_k=p_k(\boldsymbol{\beta}),\hspace{3mm}k=1,\cdots,a$
$$
という構造であるとの帰無仮説の下では、母数$\boldsymbol{\beta}$の最尤推定量を$\tilde{\boldsymbol{\beta}}$として$p_i(\tilde{\boldsymbol{\beta}})$という最尤推定量が得られる。
統計量に関して
$$
2\log\bigg[\bigg\{\bigg(\frac{y_1}{n}^{y_1} \bigg)\cdots \bigg(\frac{y_a}{n}^{y_a} \bigg) \bigg\}\bigg/ \bigg]=2\sum_{k=1}^ay_k\log\frac{y_k}{np_k(\boldsymbol{\tilde{\beta}})}
$$
という公式が得られる。これを尤度比
$$
\lambda=\frac{L(p_1(\tilde{\boldsymbol{\beta}},\cdots,p_a(\tilde{\boldsymbol{\beta}}))}{L(y_1/n,\cdots,y_a/n)}
$$
を用いて$-2\log\lambda$と表す。
$$
-2\log \lambda=2\sum (観測度数)\log \frac{(観測度数)}{(理論度数)}
$$
のようになる。
$-2\log \lambda$はモデルが真であるとの帰無仮説の下で漸近的に$\chi^2$分布に従い、自由度は$\nu$である。

In [193]:
-2*np.sum(npk*np.log(df1['度数'].values / npk))

9.449717509427995

#### 分布の適合度検定
原子核崩壊で一定時間に対極に到達した放射性物質からの$\alpha$粒子を2608回観測したデータで、ポアソン分布がよく適合する例として有名なものである。

In [197]:
df2 = pd.DataFrame({'到達数k':[0,1,2,3,4,5,6,7,8,9,10],
                    '観測度数yk':[57,203,383,525,532,408,273,139,45,27,16],
                    '理論度数yk_hat':[54.399,210.523,407.361,525.496,508.418,393.515,523.817,140.325,67.882,29.189,17.075]})
df2

    到達数k  観測度数yk  理論度数yk_hat
0      0      57      54.399
1      1     203     210.523
2      2     383     407.361
3      3     525     525.496
4      4     532     508.418
5      5     408     393.515
6      6     273     523.817
7      7     139     140.325
8      8      45      67.882
9      9      27      29.189
10    10      16      17.075

In [278]:
import math

n = df2['観測度数yk'].sum()
lambda_tilde = np.round(np.sum(df2['到達数k']*df2['観測度数yk'])/n,2)
print('lambda ',lambda_tilde)
k = np.arange(11)
pk = np.exp(-lambda_tilde)*lambda_tilde**k / [math.factorial(i) for i in k]
yk_hat = n*pk
print('理論度数\n',yk_hat)

chi2_value = np.sum((df2['観測度数yk'] - yk_hat)**2/yk_hat)
print('chi2 value ', chi2_value)

nu = len(df2) - 1- 1
print('自由度 ', nu)

p_value = chi2.sf(chi2_value, df=nu)
print('p value ', p_value)

lambda  3.87
理論度数
 [ 54.39862746 210.52268827 407.36140181 525.49620833 508.41758156
 393.51520813 253.81730924 140.3247124   67.88207962  29.18929424
  11.29625687]
chi2 value  14.775903340895029
自由度  9
p value  0.09727832746645369

#### 分割表における独立性検定
各個体を2種の属性に従って2重分類して得られる表を2次元の分割表という。
2重分類の独立性を統計的に検証するには正規確率に関する独立モデル
$$
H_0:p_{ij}=p_i\cdot p_j
$$
の適合度検定を行えばよい。これを独立性の検定という。
この帰無仮説の下で最尤推定量は、
$$
\tilde{p}_{ij}=\frac{y_{i\cdot}}{n}\frac{y_{\cdot j}}{n}
$$
で与えられる。これからセル$(i,j)$のあてはめ度数
$$
\hat{y}_{ij}=n\frac{y_{i\cdot}}{n}\frac{y_{\cdot j}}{n}=\frac{y_{i\cdot}y_{\cdot j}}{n}
$$
が得られ、$\chi^2$適合度統計量
$$
\chi^2=\sum_{i=1}^a\sum_{j=1}^b\bigg\{\bigg(y_{ij}-\frac{y_{i\cdot}y_{\cdot j}}{n} \bigg)^2 \bigg/ \bigg(\frac{y_{i\cdot}y_{\cdot j}}{n} \bigg) \bigg\}
$$
が導かれる。自由度は$p_{\cdot\cdot}=1$の制約から$H_0$の下での母数が$(a-1)+(b-1)$だけあるので
$$
\nu=ab-1-(a-1+b-1)=(a-1)(b-1)
$$
となる。

In [255]:
table = pd.DataFrame({'優':[4,8,6],'良':[2,4,3],'可':[3,6,6]},
                     index=['優','良','可'])
table

   優  良  可
優  4  2  3
良  8  4  6
可  6  3  6

In [279]:
n = table.sum().sum()
pi = np.array(table.sum(axis=1)).reshape(-1,1)
pj = np.array(table.sum(axis=0)).reshape(1,-1)

p_tilde = pi*pj/n**2
y_hat = pi*pj/n

chi2_value = np.sum(np.sum((table - y_hat)**2/y_hat))
print('chi2 value ', chi2_value)

a, b = table.shape
nu = (a-1)*(b-1)
print('自由度 ', nu)

p_value = chi2.sf(chi2_value, df=nu)
print('p value ', p_value)

chi2 value  0.18666666666666684
自由度  4
p value  0.9959062029218693

### 2つの二項分布の比較
次の表(table1)はある工程の改善前後の不良率を比較するためにそれぞれ標本を取り、良・不良に従って分類したものである。
また、表(table2)は予防注射後での発生比率を比較し、処置の効果があったか否かを判定することが目的のものである。

In [38]:
table1 = pd.DataFrame({'良':[2422,2892],'不良':[439,447]}, index=['改善前','改善後'])
table2 = pd.DataFrame({'かからなかった':[1625,1022],'かかった':[5,11]}, index=['した','しない'])
print(table1)
print(table2)

        良   不良
改善前  2422  439
改善後  2892  447
     かからなかった  かかった
した      1625     5
しない     1022    11

表table1については工程の改善前後の不良率をそれぞれ$p_1,p_2$、また表table2については駐車の有無による有効率を$p_1,p_2$として帰無仮説
$$
H_0:p_1=p_2
$$
の検定に興味がもたれる。
表table1やtable2を次のように一般に次の表のように表してから、

|群|0|1||
|-|-|-|-|
|1|$$y_{11}$$|$$y_{12}$$|$$n_1={1\cdot}$$|
|2|$$y_{21}$$|$$y_{22}$$|$$n_2={2\cdot}$$|

|群|0|1|
|-|-|-|
|1|$$1-p_{1}$$|$$p_{1}$$|
|2|$$1-p_{2}$$|$$p_{2}$$|

正規確率の推定量を
$$
\tilde{p}_1=\frac{y_{12}}{n_1},\hspace{3mm}\tilde{p}_2=\frac{y_{22}}{n_2}
$$
とすると、$\tilde{p}_1-\tilde{p}_2$は帰無仮説
$$
H_0:p_1=p_2(=p)
$$
の下で期待値は$0$、分散は
$$
\begin{align}
V(\tilde{p}_1-\tilde{p}_2)&=V(\tilde{p}_1)+V(\tilde{p}_2)\\
&=\bigg(\frac{1}{n_1}+\frac{1}{n_2} \bigg)p(1-p)
\end{align}
$$

となり、また漸近分布は中心極限定理より、正規分布
$$
N\bigg(0, \bigg(\frac{1}{n_1}+\frac{1}{n_2} \bigg)p(1-p)\bigg)
$$
となる、いま帰無仮説$H_0$のもとで考えるとして、共通の$p$を
$$
\tilde{p}=\frac{y_{12}+y_{22}}{n_1+n_2}
$$
で推定する。
基準化した統計量
$$
u=\frac{\tilde{p}_1-\tilde{p}_2}{\sqrt{\bigg(\frac{1}{n_1}+\frac{1}{n_2} \bigg)\tilde{p}(1-\tilde{p})}}
$$
を定義すると、$u$は$H_0$の下で漸近的に標準正規分布$N(0,1)$に従う。
したがって$u^2$の漸近分布は自由度$1$の$\chi^2$分布$\chi^2(1)$となる。
$u^2$は簡単な式変形により
$$
u^2=\frac{y_{\cdot\cdot}(y_{11}y_{22}-y_{12}y_{21})^2}{y_{1\cdot}y_{2\cdot}y_{\cdot 1}y_{\cdot 2}}
$$
と表される。

In [299]:
n2 = table2.sum().sum()
pi2 = table2.sum(axis=1)
pj2 = table2.sum(axis=0)

chi2_value = n2*(table2.iloc[0,0]*table2.iloc[1,1]-table2.iloc[0,1]*table2.iloc[1,0])**2 / (pi2[0]*pi2[1]*pj2[0]*pj2[1])
print('chi2 value ', chi2_value)

a, b = table2.shape 
nu = (a-1)*(b-1)
print('自由度 ', nu)

p_value = chi2.sf(chi2_value, df=nu)
print('p value ', p_value)

chi2 value  6.084865105188665
自由度  1
p value  0.013634477721305832

### 多項分布の一様性検定
#### 一様性検定
確率が等しいことの検定は3つ以上の多項分布の一様性の検定にもそのまま拡張される。
すれは数学的には一様性の帰無仮説
$$
H_0:(p_{i1},p_{i2},p_{i3})=(p_1,p_2,p_3),\hspace{3mm}i=1,\cdots,10
$$
の検定として定式化される。
これは、検定統計量として適合度の$\chi^2$統計量が導かれる。

In [42]:
table3 = pd.DataFrame({'軽傷':[148,111,645,165,383,96,98,199,59,262],
                       '中傷':[444,352,1911,771,1829,293,330,874,199,1320],
                       '重傷':[86,49,328,119,311,47,58,155,30,236]},
                       index=['1.専門的・技術敵職員','2.管理職','3.事務従事者','4.販売従事者','5.農林漁業採鉱従事者',
                              '6.運輸通信従事者','7.技能工','8.生産工程従事者','9.サービス業','10.無職'])
table3

              軽傷    中傷   重傷
1.専門的・技術敵職員  148   444   86
2.管理職        111   352   49
3.事務従事者      645  1911  328
4.販売従事者      165   771  119
5.農林漁業採鉱従事者  383  1829  311
6.運輸通信従事者     96   293   47
7.技能工         98   330   58
8.生産工程従事者    199   874  155
9.サービス業       59   199   30
10.無職        262  1320  236

#### カイ二乗統計量の分解
統括的な$\chi^2$統計量をある2行間の差を表す成分、あるいは行をいくつかの群に分類したときの群間の差を表す成分に分解することができる。
たとえば一般性を失うことなく、$\{1,2,3,\cdots,p+q\}$を分けた2群を
$$
I_1=\{1,\cdots,p\},\hspace{3mm}I_2=\{p+1,\cdots,p+q\}
$$
とするとき、群間の差を表す$\chi^2$成分は
$$
\chi^2(I_1;I_2)=\frac{y_{\cdot\cdot}\sum_{j=1}^b(\sum_{l}^{(1)}y_{lj}/\sum_{l}^{(1)}y_{l\cdot}-\sum_{l}^{(2)}y_{lj}/\sum_{l}^{(2)}y_{l\cdot})^2/y_{\cdot j}}{(1/\sum_{l}^{(1)}y_{l\cdot})+(1/\sum_{l}^{(2)}y_{l\cdot})}
$$
で与えられる。ここで$l$に関する和は、$I_1,I_2$の上でそれぞれ
$$
\sum_l^{(1)}=\sum_{l=1}^p,\hspace{3mm}\sum_l^{(2)}=\sum_{l=p+1}^{p+q}
$$
のようにとられるものとする。
これを用いて全体の$chi^2$をたとえば
$$
\chi^2=\chi^2(1;2)+\chi^2(1,2;3)+\cdots+\chi^2(1,\cdots,a-1;a)
$$
のように分解することができる。たとえば$a=3$の場合に
$$
\chi^2=\chi^2(1;2)+\chi^2(1,2;3)=\chi^2(1;3)+\chi^2(1,3;2)=\chi^2(2;3)+\chi^2(2,3;1)
$$
が成り立つことがわかる。また$a=4$では
$$
\chi^2=\chi^2(1;2)+\chi^2(3;4)+\chi^2(1,2;3,4)
$$
のように分解することもできる。
あらゆる組み合わせについてこのような$\chi^2$成分を計算し、群内は均一に、かつ群間の$\chi^2$成分はなるべく大きくなるように群分けすることが考えられる。

In [160]:
result = np.zeros((10,10))
for i in range(10):
    for j in range(10):
        tbl = table3.iloc[[i,j],:]
        ydd = table3.sum().sum()
        result[i,j] = np.sum(((tbl.T / tbl.sum(axis=1)).T.diff().iloc[1,:])**2 / table3.sum(axis=0))*ydd / np.sum(1/tbl.sum(axis=1))

In [169]:
pd.DataFrame(result)[[9,4,3,7,6,8,1,0,5,2]].T[[9,4,3,7,6,8,1,0,5,2]]

,9,4,3,7,6,8,1,0,5,2
9,0.000000,0.725476,2.197456,1.591670,8.546159,6.854245,16.353331,18.556099,14.087592,47.621240
4,0.725476,0.000000,0.807398,0.743556,6.847609,5.218390,13.451053,16.797279,11.792012,46.689386
3,2.197456,0.807398,0.000000,1.253600,5.141741,3.576242,8.683472,12.780855,8.490641,24.348935
7,1.591670,0.743556,1.253600,0.000000,3.672435,3.446429,9.081313,9.616972,7.620018,22.063659
6,8.546159,6.847609,5.141741,3.672435,0.000000,0.396743,1.509496,0.800898,0.707254,1.376599
8,6.854245,5.218390,3.576242,3.446429,0.396743,0.000000,0.258340,1.449686,0.332197,1.010212
1,16.353331,13.451053,8.683472,9.081313,1.509496,0.258340,0.000000,2.821910,0.384678,1.683113
0,18.556099,16.797279,12.780855,9.616972,0.800898,1.449686,2.821910,0.000000,0.924655,0.925971
5,14.087592,11.792012,8.490641,7.620018,0.707254,0.332197,0.384678,0.924655,0.000000,0.184708
2,47.621240,46.689386,24.348935,22.063659,1.376599,1.010212,1.683113,0.925971,0.184708,0.000000

明らかに職業に関する2群
$$
I_1=\{10,5,4,8 \},\hspace{3mm}I_2=\{7,9,2,1,6,3 \}
$$
への群分けを示唆する。実際にこの2群間の$\chi^2$は、次のようになる。

In [165]:
tbl1 = table3.iloc[[9.4,7,3],:]
tbl2 = table3.iloc[[0.1,2,5,6,8],:]

table3.sum().sum()*np.sum((tbl1.sum(axis=0) / tbl1.sum().sum() - tbl2.sum(axis=0) / tbl2.sum().sum())**2 / table3.sum(axis=0)) / (1 / tbl1.sum().sum() + 1 / tbl2.sum().sum())

65.64512578420724

一方、列に関し同様の考えを適用した結果からは
$$
J_1=\{1\},\hspace{3mm}J_2=\{2,3 \}
$$
という群分けが得られた。
$I_1,I_2$および$J_1,J_2$の各組合せを区別する新しい母数
$$
\lambda_{I_1,J_1},\lambda_{I_1,J_2},\lambda_{I_2,J_1},\lambda_{I_2,J_2}
$$
を導入して、完全独立モデル$p_{ij}=p_ip_j$を
$$
p_{ij}=p_ip_j\lambda_{IJ},\hspace{3mm}i\in I,j\in J
$$
と修正した交互作用のモデルである。$\lambda_{IJ}$のうち独立な母数は$(2-1)(2-1)=1$個である。
このモデルを仮定したときのセルの度数の最尤推定量は
$$
\tilde{m}_{ij}=y_iy_jY_{ij}/(R_IC_J),\hspace{3mm}i\in I,j\in J
$$
で与えられる。ただし、
$$
Y_{IJ}=\sum_{i\in I}\sum_{j\in J}y_{ij},\hspace{3mm}R_{I}=\sum_{i\in I}y_{i\cdot},\hspace{3mm}C_{J}=\sum_{j\in J}y_{\cdot j}
$$
である。

#### 順序カテゴリのモデル化
順序カテゴリに対するもう一つのアプローチは、背景に正規分布やロジスティック分布のような連続分布を想定し、それがいくつかの区分点で区切られた頻度データとして観測されたとしてモデル化するものである。

### 分割表の対称性の検定
#### 対称性
次の表は無細工に選ばれた$n=175$人のパネラーの2度の選挙における投票パターンを示したものである。
対角線にデータが集中するのは自明であり、前節までの独立性の検定は意味がない。
帰無仮説
$$
H_0:p_{ij}=p_{ji},\hspace{3mm}1\leq i < j \leq a
$$
の検定に興味がもたれる。これは正方な分割表における対称性の適合度検定と呼ばれる。

In [306]:
table4 = pd.DataFrame({'保守党':[68,12,12],'労働党':[1,60,3],'自由党':[1,5,13]},
                      index={'保守党','労働党','自由党'})
table4

     保守党  労働党  自由党
保守党   68    1    1
自由党   12   60    5
労働党   12    3   13

$(i,j)$セルの生起確率を$p_{ij}$で表すと確率分布は
$$
\frac{n!}{\prod_i\prod_j y_{ij}!}\prod_i\prod_jp_{ij}^{y_{ij}},\hspace{3mm}p_{\cdot\cdot}=1
$$
において$p_{ij}=p_{ji}$と置き、最尤推定量を求めると
$$
\tilde{p}_{ii}=y_{ii}/n,\hspace{3mm}\tilde{p}_{ij}=\tilde{p}_{ji}=(y_{ij}+y_{ji})/(2n)
$$
が得られ、これから適合度の$\chi^2$統計量
$$
\begin{align}
\chi^2&=\sum_i\sum_j\bigg( y_{ij}-\frac{y_{ij}+y_{ji}}{2} \bigg)^2\bigg/ \bigg(\frac{y_{ij}+y_{ji}}{2} \bigg)\\
&=\sum_{i<j}(y_{ij}-y_{ji})^2/(y_{ij}+y_{ji})
\end{align}
$$
が得られる。投票パターンのデータに対しては、$\tilde{p}_{ij}$は次のようになる。

In [314]:
n = table4.sum().sum()
p_tilde = (table4 + np.array(table4).T) / (2*n)

chi2_value = np.sum(np.sum((table4 - p_tilde*n)**2/(p_tilde*n)))
print('chi2 value ', chi2_value)

nu = 3
print('自由度 ', nu)

p_value = chi2.sf(chi2_value, df=nu)
print('p value ', p_value)

chi2 value  19.115384615384617
自由度  3
p value  0.00025878312200729837

#### 周辺対称性と準対称性
対称性の仮説は次の2つの仮説に分解される。

周辺対称性$H_{01}:p_{i\cdot}=p_{\cdot i},\hspace{3mm}i=1,\cdots,a$

準対称性$H_{02}:p_{ij}p_{ja}p_{ai}=p_{ji}p_{ia}p_{aj},\hspace{3mm}1\leq i<j<a$

仮説$H_{01}$の自由度は、$p_{\cdot\cdot}=1$により$1$だけ減じて
$$
\nu_{01}=a-1
$$
$H_{02}$については
$$
\nu_{02}=_aC_2-(a-1)=_{a-1}C_2
$$
となる。周辺対称性の意味は自明である。
いま、保守党から労働党に、労働党から自由党に、そして自由党から保守党に同程度の推移があったとすると、各党の総得票数に変化がなく周辺分布は保ったまま、対称性は崩れる。このような意味の非対称性がないとするのが準対称性の仮説である。なお、この仮説はすべての3つの組に対して
$$
p_{ij}p_{jk}p_{ki}=p_{ji}p_{ik}p_{kj}
$$
が成り立つことと同値である。

||保守党|労働党|自由党|
|-|-|-|-|
|保守党|$$-\Delta$$|$$\Delta$$|0|
|労働党|0|$$-\Delta$$|$$\Delta$$|
|自由党|$$\Delta$$|0|$$-\Delta$$|

3すくみがないこと(準対称性)の検定はブラッドリー・テリーのモデルの適合度検定に帰着する。

### ブラッドリー・テリーのモデル
次の表は1981年のパリーグ公式戦の勝敗表である。
この表では$y_{ij}$はチーム$i$がチーム$j$に勝った回数を表す。
いま、チーム$i$がチーム$j$に勝つ確率を$p_{ij}$と表し、引き分けはないものとすると$y_{ij}$は、二項分布
$$
P(Y_{ij}=y_{ij})=_{y_{ij}+y_{ji}}C_{y_{ij}}(p_{ij})^{y_{ij}}(p_{ji})^{y_{ji}},\hspace{3mm}(p_{ij}+p_{ji}=1)
$$
に従うと考えられる。従って表全体では、すべての組合せについての積
$$
f_\boldsymbol{p}(\boldsymbol{y})=\prod_{i\leq i <j\leq6} {}_{y_{ij}+y_{ji}}C_{y_{ij}}(p_{ij})^{y_{ij}}(p_{ji})^{y_{ji}}
$$
が確率分布になる。$\boldsymbol{p},\boldsymbol{y}$はすべて$p_{ij}$と$y_{ij}$のベクトルである。
この場合に勝敗の確率を記述するモデルとしてよく用いられるのがブラッドリー・テリーのモデル
$$
p_{ij}=\frac{\theta_i}{\theta_i+\theta_j},\hspace{3mm}p_{ji}=\frac{\theta_j}{\theta_i+\theta_j}
$$
である。これは各チームには強さを表すある正数$\theta_i(i=1,\cdots,6)$が対応しており、ある2チーム$i,j$が対戦したときの勝敗の確率を表す。
これが満たされれば、
$$
\begin{align}
p_{ij}p_{jk}p_{ki}&=\frac{\theta_i\theta_j\theta_k}{(\theta_i+\theta_j)(\theta_j+\theta_k)(\theta_k+\theta_i)}\\
&=p_{ji}p_{ik}p_{kj}
\end{align}
$$
が成り立つ。$p_{ij}p_{jk}p_{ki}>p_{ji}p_{ik}p_{kj}$のとき$i$が$j$に強く、$j$が$k$に強く、$k$が$j$に強いという三すくみが生じるから、ブラッドリー・テリーのモデルは三すくみが無いモデルということができる。
$f_\boldsymbol{p}(\boldsymbol{y})$を尤度$L(\boldsymbol{p})$としてこれに、$p_{ij},p_{ji}$を代入すると、対数尤度は
$$
\log L(\boldsymbol{p})=\sum_{1\leq i \leq j \leq a}\{\log r_{ij}C_{y_{ij}}-r_{ij}\log (\theta_i+\theta_j) \}\sum_{i\cdot}\log\theta_i
$$
となる。
ただしチーム数を$a$とし、$i$と$j$の対戦数を$r_{ij}=y_{ij}+y_{ji}$、$i$の総勝ち数を$y_{i\cdot}=\sum_{j(\neq i)}y_{ij}$とおいた。
この式を$\theta_i$で偏微分して$0$とおくと、
$$
\hat{\theta}_i\sum_{j(\neq i)}\frac{r_{ij}}{\hat{\theta}_i+\hat{\theta}_j}=y_{i\cdot}
$$
が得られる。ここで$\hat{\theta}_i$は相対的な大きさしか意味がないので、$K$を適当な定数として
$$
\sum_{i=1}^a\hat{\theta}_i=K
$$
という式を付加して解くことができる。
実際には次のような反復法で解くことになる。いまある段階での近似値を$\hat{\theta}_i^0(i=1,\cdots,a)$とする。このとき近似値
$$
\hat{\theta}_i=y_{i\cdot}\bigg/\sum_{j(\neq i)}\frac{r_{ij}}{\theta_i^0+\theta_j^0}
$$
を条件を満たすようにスケーリングして、次段階の近似値
$$
\hat{\theta}_i^1=\frac{K\hat{\theta}_i}{\sum\hat{\theta}}_i
$$
とし、この手順を収束するまで繰り返す。
適合度の自由度は${}_{a-1}C_{2}$である。

In [341]:
table5 = pd.DataFrame({'ファイターズ':[0,12,16,12,10,4],
                       'ブレーブス':[14,0,9,17,10,8],
                       'ライオンズ':[7,15,0,12,11,12],
                       'オリオンズ':[13,8,12,0,12,16],
                       'ホークス':[16,16,14,13,0,13],
                       'バッファローズ':[18,17,12,7,11,0]})
table5

   ファイターズ  ブレーブス  ライオンズ  オリオンズ  ホークス  バッファローズ
0       0     14      7     13    16       18
1      12      0     15      8    16       17
2      16      9      0     12    14       12
3      12     17     12      0    13        7
4      10     10     11     12     0       11
5       4      8     12     16    13        0

In [409]:
K = 100
n = table5.sum().sum()

yi = table5.sum(axis=1)
rij = np.array(table5)+np.array(table5).T
idx=np.arange(len(table5))
thetas = np.ones(len(table5)) * K / len(table5)

for _ in range(5):
    thetas_new = np.array([np.sum(yi[i] / (rij[i,idx!=i] / (thetas[i]+thetas[idx!=i]))) for i in range(len(table5))])
    thetas  = thetas_new * K / np.sum(thetas_new)
p_tilde = thetas.reshape(-1,1) / (thetas.reshape(-1,1)+thetas.reshape(1,-1))

chi2_value = np.sum(np.sum((table5 - p_tilde*rij)**2/(p_tilde*rij)))
print('chi2 value ', chi2_value)

nu = 10
print('自由度 ', nu)

p_value = chi2.sf(chi2_value, df=nu)
print('p value ', p_value)

chi2 value  22.37859048635881
自由度  10
p value  0.013287904485372055